### ISSUE TITLE
where are data_verts.npy, raw_audio_fixed.pkl, templates.pkl and subj_seq_to_idx.pkl ?

### ISSUE THREAD

**Issue by Owen1234560** [EvelynFan/FaceFormer#1]
Hi,
I can not find data_verts.npy, raw_audio_fixed.pkl, templates.pkl and subj_seq_to_idx.pkl  in the https://voca.is.tue.mpg.de/index.html.
Could you help me ?
Thanks.

**Comment by EvelynFan** [comment]
> Hi, I can not find data_verts.npy, raw_audio_fixed.pkl, templates.pkl and subj_seq_to_idx.pkl in the https://voca.is.tue.mpg.de/index.html. Could you help me ? Thanks.

Hi, please click "Download" and the Training Data (8 GB) can be found at the bottom of the page. Registration is required.
