### ISSUE TITLE
bugs when running demo

### ISSUE THREAD

**Issue by Rexime** [EvelynFan/FaceFormer#10]
Traceback (most recent call last):
  File "demo.py", line 205, in <module>
    main()
  File "demo.py", line 201, in main
    test_model(args)
  File "/data2/aotenglong/anaconda3/envs/meshtalk/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "demo.py", line 44, in test_model
    temp = templates[args.subject]
KeyError: 'FaceTalk_170809_00138_TA'

**Comment by EvelynFan** [comment]
> Traceback (most recent call last): File "demo.py", line 205, in main() File "demo.py", line 201, in main test_model(args) File "/data2/aotenglong/anaconda3/envs/meshtalk/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context return func(*args, **kwargs) File "demo.py", line 44, in test_model temp = templates[args.subject] KeyError: 'FaceTalk_170809_00138_TA'

The file "templates.pkl" in the folder VOCASET should be downloaded from the website (https://voca.is.tue.mpg.de/). You may print the keys in your "templates.pkl" file and check if it contains the key 'FaceTalk_170809_00138_TA'.

**Comment by Rexime** [comment]
I did use the "templates.pkl" in the folder VOCASET , and I printed the keys, this is the output :

dict_keys(['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6'])

**Comment by EvelynFan** [comment]
> I did use the "templates.pkl" in the folder VOCASET , and I printed the keys, this is the output :
> 
> dict_keys(['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6'])

According to your print information, it's the "templates.pkl" file in the biwi folder. You need to download a different "templates.pkl" from https://voca.is.tue.mpg.de/.

**Comment by Rexime** [comment]
thanks a lot!! I mixed them up.. Problem solved!
