### ISSUE TITLE
The output video has no sound

### ISSUE THREAD

**Issue by wangjio** [EvelynFan/FaceFormer#11]
Hi, thanks for your great work!
My output video has no sound. Do you have any idea?

python demo.py --model_name vocaset --wav_path "demo/wav/test.wav" --dataset vocaset --vertice_dim 15069 --feature_dim 64 --period 30  --fps 30  --train_subjects "FaceTalk_170728_03272_TA FaceTalk_170904_00128_TA FaceTalk_170725_00137_TA FaceTalk_170915_00223_TA FaceTalk_170811_03274_TA FaceTalk_170913_03279_TA FaceTalk_170904_03276_TA FaceTalk_170912_03278_TA" --test_subjects "FaceTalk_170809_00138_TA FaceTalk_170731_00024_TA" --condition FaceTalk_170913_03279_TA --subject FaceTalk_170809_00138_TA

**Comment by EvelynFan** [comment]
> Hi, thanks for your great work! My output video has no sound. Do you have any idea?
> 
> python demo.py --model_name vocaset --wav_path "demo/wav/test.wav" --dataset vocaset --vertice_dim 15069 --feature_dim 64 --period 30 --fps 30 --train_subjects "FaceTalk_170728_03272_TA FaceTalk_170904_00128_TA FaceTalk_170725_00137_TA FaceTalk_170915_00223_TA FaceTalk_170811_03274_TA FaceTalk_170913_03279_TA FaceTalk_170904_03276_TA FaceTalk_170912_03278_TA" --test_subjects "FaceTalk_170809_00138_TA FaceTalk_170731_00024_TA" --condition FaceTalk_170913_03279_TA --subject FaceTalk_170809_00138_TA

Yes, the output video has no sound (because my system lacks the audio codec). You can get a video with sound by running the following command:

`ffmpeg  -i  test.wav  -i  video_no_sound.mp4 -vcodec h264 -ac 2 -channel_layout stereo -qscale 0 video_with_sound.mp4`

**Comment by wangjio** [comment]
Thanks!
