### ISSUE TITLE
Evaluation Results

### ISSUE THREAD

**Issue by yangdaowu** [EvelynFan/FaceFormer#14]
Hello, I want to know how to get the results and relevant evaluation indicators in the paper. Thank you for your answer

**Comment by EvelynFan** [comment]
> Hello, I want to know how to get the results and relevant evaluation indicators in the paper. Thank you for your answer

Hi, the evaluation results are obtained by comparing the predictions (the vertices' coordinates) and the processed 3D face geometry data. For each frame, the maximal L2 error of all lip vertices is defined as the lip error. Basically, we first select a lip region (a set of vertices) from the face mesh. Then, we calculate the maximal L2 error for each frame and compute the average over all frames.

**Comment by yangdaowu** [comment]
Thank you for your answer. I also want to know how to calculate the two indicators of lip sync evaluation and Realization in this paper. I haven't found the relevant code. Can you provide it? Thank you again for your answer.

**Comment by EvelynFan** [comment]
> Thank you for your answer. I also want to know how to calculate the two indicators of lip sync evaluation and Realization in this paper. I haven't found the relevant code. Can you provide it? Thank you again for your answer.

The evaluation results in terms of Lip Sync and Realism are based on the user study. We conduct user studies on AMT.
The Turkers are instructed to judge the videos in terms of Lip Sync and Realism. Their answers are returned by the AMT platform and the respective percentage values can be easily obtained.

**Comment by yangdaowu** [comment]
Thank you for your answer.  I get it.

**Comment by yangdaowu** [comment]
Hello, there is a problem, how should I get the maximum L2 error of each frame and calculate the average of all frames, I can only see the change of LOSS

![image](https://user-images.githubusercontent.com/64669901/163673535-f4822e3a-2fbd-4e0a-af6e-7af359301335.png)

**Comment by EvelynFan** [comment]
For the training, we use the MSE loss instead of the maximal L2 error. After the training is finished, we evaluate the trained model using the maximal L2 error of all lip vertices. But the maximal L2 error is just for lip-sync evaluation. For this task, we actually focus on the animation quality, and thus a qualitative evaluation would be more proper. Please refer to this issue #12

**Comment by yangdaowu** [comment]
Thank you for your answer. I get it.
