### ISSUE TITLE
test_subjects

### ISSUE THREAD

**Issue by yangdaowu** [EvelynFan/FaceFormer#15]
Hello, I found that test_subjects is not used, what is the reason?

![image](https://user-images.githubusercontent.com/64669901/163818883-2781bf0f-a5dd-4e3e-8555-d3187dd5b5fa.png)

**Comment by EvelynFan** [comment]
> Hello, I found that test_subjects is not used, what is the reason?
> 
> ![image](https://user-images.githubusercontent.com/64669901/163818883-2781bf0f-a5dd-4e3e-8555-d3187dd5b5fa.png)

Hi, the test_subjects are unseen subjects. They are not used in the training. For the train/val/test splits, we follow the same setting in VOCA (https://github.com/TimoBolkart/voca/blob/master/config_parser.py).

**Comment by yangdaowu** [comment]
Thank you for your answer.
