### ISSUE TITLE
download data_verts.npy, raw_audio_fixed.pkl, templates.pkl and subj_seq_to_idx.pkl

### ISSUE THREAD

**Issue by qiuyuzhao** [EvelynFan/FaceFormer#19]
how to download  data_verts.npy, raw_audio_fixed.pkl, templates.pkl and subj_seq_to_idx.pkl？ where to find these，I find VOCASET all pictures and voice。

**Comment by Johnren1111** [comment]
I also meet this problem！

**Comment by gerwang** [comment]
I believe it's in the "Training Data" section in https://voca.is.tue.mpg.de/download.php
