### ISSUE TITLE
The resulting video has no sound

### ISSUE THREAD

**Issue by Johnren1111** [EvelynFan/FaceFormer#21]
python demo.py --model_name biwi --wav_path "demo/wav/test.wav" --dataset BIWI --vertice_dim 70110  --feature_dim 128 --period 25 --fps 25 --train_subjects "F2 F3 F4 M3 M4 M5" --test_subjects "F1 F5 F6 F7 F8 M1 M2 M6" --condition M3 --subject M1
Some weights of the model checkpoint at facebook/wav2vec2-base-960h were not used when initializing Wav2Vec2Model: ['lm_head.weight', 'lm_head.bias']
- This IS expected if you are initializing Wav2Vec2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/johnren/anaconda3/lib/python3.8/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
rendering:  test
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/johnren/Desktop/FaceFormer/demo/output/tmpraurad03.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.76.100
  Duration: 00:00:11.48, start: 0.000000, bitrate: 986 kb/s
    Stream #0:0(und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 800x800 [SAR 1:1 DAR 1:1], 985 kb/s, 25 fps, 25 tbr, 12800 tbn, 25 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Please use -q:a or -q:v, -qscale is ambiguous
File 'demo/output/test_M1_condition_M3.mp4' already exists. Overwrite ? [y/N] y
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg4 (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x562c16b07400] using SAR=1/1
[libx264 @ 0x562c16b07400] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x562c16b07400] profile High, level 3.1
[libx264 @ 0x562c16b07400] 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=24 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'demo/output/test_M1_condition_M3.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.29.100
    Stream #0:0(und): Video: h264 (libx264) (avc1 / 0x31637661), yuv420p, 800x800 [SAR 1:1 DAR 1:1], q=-1--1, 25 fps, 12800 tbn, 25 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc58.54.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=  287 fps=0.0 q=-1.0 Lsize=     338kB time=00:00:11.36 bitrate= 244.1kbits/s speed=23.1x    
video:334kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.242142%
[libx264 @ 0x562c16b07400] frame I:2     Avg QP:16.06  size:  7228
[libx264 @ 0x562c16b07400] frame P:78    Avg QP:21.98  size:  2355
[libx264 @ 0x562c16b07400] frame B:207   Avg QP:24.91  size:   693
[libx264 @ 0x562c16b07400] consecutive B-frames:  2.8%  1.4%  5.2% 90.6%
[libx264 @ 0x562c16b07400] mb I  I16..4: 29.6% 64.6%  5.9%
[libx264 @ 0x562c16b07400] mb P  I16..4:  0.9%  2.9%  0.1%  P16..4: 16.0%  3.8%  1.2%  0.0%  0.0%    skip:75.2%
[libx264 @ 0x562c16b07400] mb B  I16..4:  0.2%  0.5%  0.0%  B16..8: 14.1%  1.0%  0.0%  direct: 0.1%  skip:84.2%  L0:54.7% L1:43.3% BI: 2.0%
[libx264 @ 0x562c16b07400] 8x8 transform intra:71.8% inter:76.2%
[libx264 @ 0x562c16b07400] coded y,uvDC,uvAC intra: 33.1% 0.5% 0.0% inter: 1.3% 0.0% 0.0%
[libx264 @ 0x562c16b07400] i16 v,h,dc,p: 52% 12%  9% 27%
[libx264 @ 0x562c16b07400] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 32% 17% 41%  1%  2%  2%  1%  2%  1%
[libx264 @ 0x562c16b07400] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 29% 31% 18%  4%  3%  3%  5%  3%  4%
[libx264 @ 0x562c16b07400] i8c dc,h,v,p: 95%  2%  3%  0%
[libx264 @ 0x562c16b07400] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x562c16b07400] ref P L0: 57.5%  4.8% 25.2% 12.5%
[libx264 @ 0x562c16b07400] ref B L0: 78.1% 15.8%  6.2%
[libx264 @ 0x562c16b07400] ref B L1: 92.3%  7.7%
[libx264 @ 0x562c16b07400] kb/s:238.06

**Comment by raymondsim** [comment]
The script doesn't add sound to the resulting video. You can do it by yourself as mentioned in #11
