### ISSUE TITLE
templates.pkl for vocaset model

### ISSUE THREAD

**Issue by hannahgym** [EvelynFan/FaceFormer#34]
Amazing work! could you plz guide me where to find templates.pkl ?
for BIWI, it is here: FaceFormer/BIWI/templates.pkl
however I can not find it for vocaset.

Looking forward to hearing from you!

**Comment by zhuangxy** [comment]
refer to issue #19 , it's in the "Training Data" section in https://voca.is.tue.mpg.de/download.php
