### ISSUE TITLE
VOCASET data not found

### ISSUE THREAD

**Issue by FangmingTian** [EvelynFan/FaceFormer#52]
In Data section, data_verts.npy, raw_audio_fixed.pkl, templates.pkl and subj_seq_to_idx.pkl are required, but I couldn't find them on https://voca.is.tue.mpg.de/. All downloaded files have the zip extension. Where can I find the required files or what operation should I do? Anyone can help me?

**Comment by wzx7084** [comment]
You can download them on https://voca.is.tue.mpg.de/. Click the Download button at the top to go to the new screen,you'll see training data at the bottom of the page.  data_verts.npy, raw_audio_fixed.pkl, templates.pkl and subj_seq_to_idx.pkl in this zip.

**Comment by wzx7084** [comment]
> 
You can download them on https://voca.is.tue.mpg.de/. Click the Download button at the top to go to the new screen,you'll see training data at the bottom of the page. data_verts.npy, raw_audio_fixed.pkl, templates.pkl and subj_seq_to_idx.pkl in this zip.
