### ISSUE TITLE
文件在哪里

### ISSUE THREAD

**Issue by zhengshi119** [EvelynFan/FaceFormer#61]
这几个vocaset/vertices_npy, vocaset/wav and vocaset/templates具体在voca的哪里，谁能告诉我？

**Comment by xmaple04** [comment]
你找到文件了吗？看你主动关闭了这个issue，是不是找到了？
where did you find these files?

**Comment by xmaple04** [comment]
> 这几个vocaset/vertices_npy, vocaset/wav and vocaset/templates具体在voca的哪里，谁能告诉我？

你找到文件了吗？看你主动关闭了这个issue，是不是找到了？
where did you find these files?
