### ISSUE TITLE
Run on Windows

### ISSUE THREAD

**Issue by ChairManMeow-SY** [EvelynFan/FaceFormer#67]
Thanks for authors to share this excellent job!

I just successfully ran the demo on Windows 10. It is painful to search the documents and solve some problems... Here I record it to help anyone who want to run it on windows too.

My env
OS: windows 10
GPU: GTX 3080 Ti
CPU: Intel 12th
Python with conda env

Step 1. Install packages in requirements.txt

The only thing you should pay attention to is the transformers version. Use the following command:
```
pip install transformers==4.6.1
```

Step 2. Install pyopengl
Do not use 'pip install pyopengl' directly because it offers a package lacking some libraries (It is amazing but true...).
Download the .whl file from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl)  and install it with:
```
pip install <downloaded file>
```
**Note that do not install the opengl before you have installed the pyrender!!** This will uninstall your pyopengl and install a pypi version, which lacks the necessary libraries.

Step 3. Install boost
Just do with the google instructions.

Step 4. Install mesh
Download the mesh from [here](https://github.com/johnbanq/mesh/tree/fix/MSVC_compilation) and following its readMe, i.e. 
```
pip install --no-deps --install-option="--boost-location=<path_to_your_boost>" --verbose --no-cache-dir .
```

Step 5. Install ffmpeg
You can find a pre-compiled version from ffmpeg website. Just double click it.

Step 6. Revise the demo.py
Finally we have install all the necessary packages. But if you run the demo directly, it will throw an error: can not find osmesa.
The easist way to solve it is  to comment this line:
```
os.environ['PYOPENGL_PLATFORM'] = 'osmesa' # egl
```
The pyrender will use pyglet for off-screen rendering. Some explainations can be found [here](https://pyrender.readthedocs.io/en/latest/examples/offscreen.html#running-the-renderer).

Then replace the render_sequence(args) funciton with the following code
```
def render_sequence(args):
    wav_path = args.wav_path
    test_name = os.path.basename(wav_path).split(".")[0]
    predicted_vertices_path = os.path.join(args.result_path,test_name+".npy")
    if args.dataset == "BIWI":
        template_file = os.path.join(args.dataset, args.render_template_path, "BIWI.ply")
    elif args.dataset == "vocaset":
        template_file = os.path.join(args.dataset, args.render_template_path, "FLAME_sample.ply")
         
    print("rendering: ", test_name)
                 
    template = Mesh(filename=template_file)
    predicted_vertices = np.load(predicted_vertices_path)
    predicted_vertices = np.reshape(predicted_vertices,(-1,args.vertice_dim//3,3))

    output_path = args.output_path
    if not os.path.exists(output_path):
        os.makedirs(output_path)

    num_frames = predicted_vertices.shape[0]
    tmp_file='./output.mp4'
    
    writer = cv2.VideoWriter(tmp_file, cv2.VideoWriter_fourcc(*'mp4v'), args.fps, (800, 800), True)
    center = np.mean(predicted_vertices[0], axis=0)

    for i_frame in range(num_frames):
        render_mesh = Mesh(predicted_vertices[i_frame], template.f)
        pred_img = render_mesh_helper(args,render_mesh, center)
        pred_img = pred_img.astype(np.uint8)
        writer.write(pred_img)

    writer.release()
    file_name = test_name+"_"+args.subject+"_condition_"+args.condition
    video_fname = os.path.join(output_path, file_name+'.mp4')
    #cmd = ('ffmpeg.exe' + ' -i {0} -pix_fmt yuv420p -qscale 0 {1}'.format(tmp_video_file.name, video_fname)).split()
    cmd='ffmpeg -i %s -i %s %s' %(tmp_file,wav_path,video_fname)
    os.system(cmd)
```
Here are two modifications: 
1. use a string file name instead of the temp file because the ffmpeg will throw a permission error.
2. use ffmpeg to put the wav and video together. This can help check the algorithm performance.

Then enjoy it now  : )

**Comment by ShaojunBian** [comment]
Thanks so much! your record helps me a lot!

**Comment by zjuyichen** [comment]
hello, when i do the step 4,  i have the problem "Running setup.py install for psbody-mesh did not run successfully.", how can i solve it ?


D:\softs\Conda\envs\faceformer\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
  D:\git_data\mesh\mesh\src\AABB_n_tree.h(9): fatal error C1083: Cannot open include file: 'CGAL/AABB_tree.h': No such file or directory
  error: command 'D:\\sofs\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  error: subprocess-exited-with-error

  × Running setup.py install for psbody-mesh did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'D:\softs\Conda\envs\faceformer\python.exe' -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'D:\\git_data\\mesh\\setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' install --record 'C:\Users\SHENYI~1\AppData\Local\Temp\pip-record-0684pn6u\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\softs\Conda\envs\faceformer\Include\psbody-mesh' '--boost-location=C:\Boost\boost_1_81_0'
  cwd: D:\git_data\mesh\
  Running setup.py install for psbody-mesh ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> psbody-mesh

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by ChairManMeow-SY** [comment]
> hello, when i do the step 4, i have the problem "Running setup.py install for psbody-mesh did not run successfully.", how can i solve it ?

Hi yichen, I notice it may be a compiling error:

**D:\git_data\mesh\mesh\src\AABB_n_tree.h(9): fatal error C1083: Cannot open include file: 'CGAL/AABB_tree.h': No such file or directory**

The compiler can not find the CGAL head file.  It is strange because the package should contain a CGAL package in the folder D:\git_data\mesh\mesh\thirdparty\ .

Please check it or you may decode it manually.

**Comment by zjuyichen** [comment]
> > hello, when i do the step 4, i have the problem "Running setup.py install for psbody-mesh did not run successfully.", how can i solve it ?
> 
> Hi yichen, I notice it may be a compile error:
> 
> **D:\git_data\mesh\mesh\src\AABB_n_tree.h(9): fatal error C1083: Cannot open include file: 'CGAL/AABB_tree.h': No such file or directory**
> 
> The compiler can not find the CGAL head file. It is strange because the package should contain a CGAL package in the folder D:\git_data\mesh\mesh\thirdparty\ .
> 
> Please check it or you may decode it manually.

thank your response, I took a very stupid mistake: i didn't git checkout the right branch……

**Comment by ChairManMeow-SY** [comment]
> > > hello, when i do the step 4, i have the problem "Running setup.py install for psbody-mesh did not run successfully.", how can i solve it ?
> > 
> > 
> > Hi yichen, I notice it may be a compile error:
> > **D:\git_data\mesh\mesh\src\AABB_n_tree.h(9): fatal error C1083: Cannot open include file: 'CGAL/AABB_tree.h': No such file or directory**
> > The compiler can not find the CGAL head file. It is strange because the package should contain a CGAL package in the folder D:\git_data\mesh\mesh\thirdparty\ .
> > Please check it or you may decode it manually.
> 
> thank your response, I took a very stupid mistake: i didn't git checkout the right branch……

Great to know the problem solved!

**Comment by Langwenchong** [comment]
hello，firstly thank your for your record,it helped me so much, but i found there is no sound in my output.mp4,have you ever encountered this problem? If so, can I ask you how to solve it

**Comment by ChairManMeow-SY** [comment]
> hello，firstly thank your for your record,it helped me so much, but i found there is no sound in my output.mp4,have you ever encountered this problem? If so, can I ask you how to solve it

hi there~可以看一下step 6的函数最后几行：

`cmd='ffmpeg -i %s -i %s %s' %(tmp_file,wav_path,video_fname)`

可以参考这个cmd，在python脚本里面对音视频组装，或者在命令行里面手动调用ffmpeg。tmp_file 指的是网络的输出文件， wav_path是输入的音频文件，video_fname是你希望保存的文件名。

**Comment by Langwenchong** [comment]
I got the program running, thank you so much😁
