### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by Sylvia-Yuju** [EvelynFan/FaceFormer#75]
When running the demo.py code, the following problem occurs, How can I solve 
![1521680011628_ pic_hd](https://user-images.githubusercontent.com/46679831/228260925-5be0a4ec-a8dd-491e-814a-fe7092e0f1cb.jpg)

**Comment by Aiedails** [comment]
Me too. So I'm simply let `tgt_mask = tgt_mask.unsqueeze(0)`and it works.

**Comment by Sylvia-Yuju** [comment]
> Me too. So I'm simply let `tgt_mask = tgt_mask.unsqueeze(0)`and it works.

Yes, I solved it like this too
