### ISSUE TITLE
这几个文件在哪下载呀 data_verts.npy, raw_audio_fixed.pkl, templates.pkl and subj_seq_to_idx.pkl ，没找到

### ISSUE THREAD

**Issue by paulllb** [EvelynFan/FaceFormer#79]
data_verts.npy, raw_audio_fixed.pkl, templates.pkl and subj_seq_to_idx.pkl  这几个文件在 https://voca.is.tue.mpg.de/download.php 不知道下载哪几个，有人可以告知一下嘛？

**Comment by paulllb** [comment]
i figure it out

**Comment by damon-93** [comment]
> i figure it out

哥，方便的话能百度网盘分享一下吗？万分感谢~我这边实在下不动。。。

**Comment by DavidKong96** [comment]
> data_verts.npy, raw_audio_fixed.pkl, templates.pkl and subj_seq_to_idx.pkl 这几个文件在 https://voca.is.tue.mpg.de/download.php 不知道下载哪几个，有人可以告知一下嘛？

can you tell me which folder should i download? ty

**Comment by zk19971101** [comment]
![res](https://github.com/EvelynFan/FaceFormer/assets/78424820/4c6e4d58-f1cc-425f-b2b7-9f9376de2e1a)
the issue link is https://github.com/Doubiiu/CodeTalker/issues/41#issuecomment-1636809958
