### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by yangdaowu** [EvelynFan/FaceFormer#8]
Hello, I have this problem.
![image](https://user-images.githubusercontent.com/64669901/160386764-3b4977bb-181a-4ddf-ace1-51c96332da1a.png)

**Comment by EvelynFan** [comment]
> Hello, I have this problem. ![image](https://user-images.githubusercontent.com/64669901/160386764-3b4977bb-181a-4ddf-ace1-51c96332da1a.png)

Did this error happen when you ran demo.py? Please note that the version of transformers is 4.6.1.

**Comment by yangdaowu** [comment]
I am an error that occurs when I run main.py, and I will also convert the version to 4.6.1.

**Comment by EvelynFan** [comment]
> I am an error that occurs when I run main.py, and I will also convert the version to 4.6.1.

Let me know if changing the version of transformers can work. I will close this issue for now. If you have other problems, feel free to reopen this issue.
