### ISSUE TITLE
Failed rendering frame

### ISSUE THREAD

**Issue by Rexime** [EvelynFan/FaceFormer#9]
Some weights of the model checkpoint at facebook/wav2vec2-base-960h were not used when initializing Wav2Vec2Model: ['lm_head.weight', 'lm_head.bias']
- This IS expected if you are initializing Wav2Vec2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/data2/mesh/FaceFormer-main/faceformer.py:22: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  bias = torch.arange(start=0, end=max_seq_len, step=period).unsqueeze(1).repeat(1,period).view(-1)//(period)
Downloading: 100%|███████████████████████████████████████| 159/159 [00:00<00:00, 77.7kB/s]
Downloading: 100%|████████████████████████████████████████| 291/291 [00:00<00:00, 145kB/s]
Downloading: 100%|███████████████████████████████████████| 163/163 [00:00<00:00, 62.7kB/s]
Downloading: 100%|█████████████████████████████████████| 85.0/85.0 [00:00<00:00, 34.9kB/s]
rendering:  test
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)

I have encountered this problem. A black screen video will be generated. I don't know how to solve it. Please help me.

**Comment by EvelynFan** [comment]
> Some weights of the model checkpoint at facebook/wav2vec2-base-960h were not used when initializing Wav2Vec2Model: ['lm_head.weight', 'lm_head.bias']
> 
> * This IS expected if you are initializing Wav2Vec2Model from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> * This IS NOT expected if you are initializing Wav2Vec2Model from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
>   Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
>   You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
>   /data2/mesh/FaceFormer-main/faceformer.py:22: UserWarning: **floordiv** is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
>   bias = torch.arange(start=0, end=max_seq_len, step=period).unsqueeze(1).repeat(1,period).view(-1)//(period)
>   Downloading: 100%|███████████████████████████████████████| 159/159 [00:00<00:00, 77.7kB/s]
>   Downloading: 100%|████████████████████████████████████████| 291/291 [00:00<00:00, 145kB/s]
>   Downloading: 100%|███████████████████████████████████████| 163/163 [00:00<00:00, 62.7kB/s]
>   Downloading: 100%|█████████████████████████████████████| 85.0/85.0 [00:00<00:00, 34.9kB/s]
>   rendering:  test
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   pyrender: Failed rendering frame
>   ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
>   built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
> 
> I have encountered this problem. A black screen video will be generated. I don't know how to solve it. Please help me.

Some people also have the same issue. Can you check #7 for some possible solutions?

**Comment by Rexime** [comment]
thanks! using pyopengl 3.1.4 solved this problem!

**Comment by mumukawayi** [comment]
Sorry to bother, I tried both pyopengl 3.1.0 and 3.1.4 but always got a whole screen of
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
Could any body leave me some idea?
