### ISSUE TITLE
@JSHZT @shivangi-aneja @xiaodongyichuan Also facing the same issue. Did you fix this problem?

### ISSUE THREAD

**Issue by JSHZT** [EvelynFan/FaceFormer#98]
@JSHZT @shivangi-aneja @xiaodongyichuan Also facing the same issue. Did you fix this problem?

_Originally posted by @Shirley-0708 in https://github.com/EvelynFan/FaceFormer/issues/43#issuecomment-1777044199_
            In fact, the modifications described above are not rigorous. I don't agree with the operation of splicing with zero vectors, because the entire sequence has been templated. According to the author's original idea, the network learns the displacement relative to a specific template, so After splicing with the template and then subtracting the template, the first frame is a neutral expression with a displacement of zero. Splicing with the zero vector makes the logic of this task wrong. The way I achieve a similar purpose is to redo the data, but this is undoubtedly expensive, but other than that, I can't think of other rigorous methods, because this data and task have a tight coupling of identity and style.hope it is of help to you！

**Comment by Shirley-0708** [comment]
@JSHZT Thanks for your prompt reply! Actually, I'm more concerned about **why the hidden_states are all the same after the audio encoder in the prediction stage**, which results in the predicted animation remaining stationary for each frame even if without the zero vectors problem. I've observed that hidden_states are clearly different during training, can this be explained by the fact that the model wasn't learned well in the training phase, and therefore when the model sees data it hasn't seen before during prediction, the hidden_states tend to be consistent? My custom dataset is Chinese, I even have thought about whether wav2vec2 in the extraction of Chinese audio features has problems. This issue troubled me for a long time, look forward to your help!
As a side note, I am trying to use 3DMM coefficients and a Chinese audio dataset to learn.
![image](https://github.com/EvelynFan/FaceFormer/assets/87968990/36d03a65-251c-4113-b945-e332562ada39)

**Comment by xiaomaofei** [comment]
我的自定义数据集是中文的，训练的效果也并不是很好。我想知道你那边解决了吗？

**Comment by JSHZT** [comment]
> @JSHZT Thanks for your prompt reply! Actually, I'm more concerned about **why the hidden_states are all the same after the audio encoder in the prediction stage**, which results in the predicted animation remaining stationary for each frame even if without the zero vectors problem. I've observed that hidden_states are clearly different during training, can this be explained by the fact that the model wasn't learned well in the training phase, and therefore when the model sees data it hasn't seen before during prediction, the hidden_states tend to be consistent? My custom dataset is Chinese, I even have thought about whether wav2vec2 in the extraction of Chinese audio features has problems. This issue troubled me for a long time, look forward to your help! As a side note, I am trying to use 3DMM coefficients and a Chinese audio dataset to learn. ![image](https://private-user-images.githubusercontent.com/87968990/278849683-36d03a65-251c-4113-b945-e332562ada39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzg2ODgsIm5iZiI6MTczMzI3ODM4OCwicGF0aCI6Ii84Nzk2ODk5MC8yNzg4NDk2ODMtMzZkMDNhNjUtMjUxYy00MTEzLWI5NDUtZTMzMjU2MmFkYTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDAyMTMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5NGUzNDA1OTFkMWQ0M2U3ODczMWNmMmIwYWM1YjkwYTQzZDZmYzZkNDI1OTc3MjRiZjcwYjY4YzQyNjI0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WaubYB6MGNHfXVv6Igngb3mtex7csSoQamQetsTNggA)

Sorry, I didn't reply in time because I didn't see the previous email. I don't know if replying now will be helpful to you. If you have not changed the audio encoder code, I think the problem is more likely to be in the data. I have not experienced a similar situation here.
